services:
  - type: web
    name: fastapi-ocr
    env: python
    region: oregon
    buildCommand: "bash render-build.sh"
    startCommand: "bash start.sh"
    envVars:
      - key: PORT
        value: 8000
      - key: API_KEY
        sync: false
    plan: free
