services:
  - type: web
    name: fastapi-ocr
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: PORT
        value: 8000
      - key: API_KEY
        sync: false
